services:
  app:
    container_name: quantum-information-seminar-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - type: bind
        source: ../
        target: /workspaces/quantum-information-seminar/
    tty: true
